# Generated by `just codegen-mcp` from the internal app OpenAPI (Group-A subset).
# DO NOT EDIT: change the backend schema, then regenerate. See
# docs/adr/0001-generate-mcp-group-a-schemas-from-internal-openapi.md.

from __future__ import annotations

from datetime import date
from enum import StrEnum
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class AddEdgeOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_id: Annotated[str, Field(title="From Id")]
    op: Annotated[Literal["add_edge"], Field(title="Op")]
    to_id: Annotated[str, Field(title="To Id")]


class AddItemOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after_id: Annotated[str | None, Field(title="After Id")] = None
    before_id: Annotated[str | None, Field(title="Before Id")] = None
    op: Annotated[Literal["add_item"], Field(title="Op")]
    proposed_id: Annotated[str | None, Field(title="Proposed Id")] = None
    subsection_id: Annotated[str, Field(title="Subsection Id")]
    text: Annotated[str, Field(title="Text")]


class AddSectionOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after_id: Annotated[str | None, Field(title="After Id")] = None
    before_id: Annotated[str | None, Field(title="Before Id")] = None
    op: Annotated[Literal["add_section"], Field(title="Op")]
    proposed_id: Annotated[str | None, Field(title="Proposed Id")] = None
    title: Annotated[str, Field(min_length=1, title="Title")]


class ChangeType(StrEnum):
    ADDED = "added"
    UPDATED = "updated"
    REMOVED = "removed"


class ChangedNodeKind(StrEnum):
    ROADMAP = "roadmap"
    SECTION = "section"
    SUBSECTION = "subsection"
    ITEM = "item"


class ChecklistItem(BaseModel):
    id: Annotated[str, Field(title="Id")]
    text: Annotated[str, Field(title="Text")]


class ChecklistItemInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    proposed_id: Annotated[str | None, Field(title="Proposed Id")] = None
    text: Annotated[str, Field(title="Text")]


class CompletionState(StrEnum):
    COMPLETE = "complete"
    INCOMPLETE = "incomplete"


class ItemState(BaseModel):
    done: Annotated[bool, Field(title="Done")]
    id: Annotated[str, Field(title="Id")]
    text: Annotated[str, Field(title="Text")]


class OverallProgress(BaseModel):
    checked_items: Annotated[int, Field(title="Checked Items")]
    percent: Annotated[int, Field(title="Percent")]
    total_items: Annotated[int, Field(title="Total Items")]


class PrereqRef(BaseModel):
    done: Annotated[bool, Field(title="Done")]
    id: Annotated[str, Field(title="Id")]
    title: Annotated[str, Field(title="Title")]


class PublishedVisibility(StrEnum):
    PUBLIC = "public"
    PRIVATE = "private"


class RemoveEdgeOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    from_id: Annotated[str, Field(title="From Id")]
    op: Annotated[Literal["remove_edge"], Field(title="Op")]
    to_id: Annotated[str, Field(title="To Id")]


class RemoveItemOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    item_id: Annotated[str, Field(title="Item Id")]
    op: Annotated[Literal["remove_item"], Field(title="Op")]


class RemoveSectionOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: Annotated[Literal["remove_section"], Field(title="Op")]
    section_id: Annotated[str, Field(title="Section Id")]


class RemoveSubsectionOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: Annotated[Literal["remove_subsection"], Field(title="Op")]
    subsection_id: Annotated[str, Field(title="Subsection Id")]


class ReorderOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after_id: Annotated[str | None, Field(title="After Id")] = None
    before_id: Annotated[str | None, Field(title="Before Id")] = None
    op: Annotated[Literal["reorder"], Field(title="Op")]
    target_id: Annotated[str, Field(title="Target Id")]


class ResourceType(StrEnum):
    ARTICLE = "article"
    VIDEO = "video"
    BOOK = "book"
    COURSE = "course"
    DOCS = "docs"
    OTHER = "other"


class ResponseFormat(StrEnum):
    CONCISE = "concise"
    DETAILED = "detailed"


class RoadmapStatus(StrEnum):
    DRAFT = "draft"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class SearchHitKind(StrEnum):
    SUBSECTION = "subsection"
    ITEM = "item"


class SectionInclude(StrEnum):
    SUBSECTIONS = "subsections"
    ITEMS = "items"
    BOTH = "both"


class SectionOverview(BaseModel):
    checked_items: Annotated[int, Field(title="Checked Items")]
    percent: Annotated[int, Field(title="Percent")]
    section_id: Annotated[str, Field(title="Section Id")]
    title: Annotated[str, Field(title="Title")]
    total_items: Annotated[int, Field(title="Total Items")]


class SectionProgress(BaseModel):
    checked_items: Annotated[int, Field(title="Checked Items")]
    percent: Annotated[int, Field(title="Percent")]
    section_id: Annotated[str, Field(title="Section Id")]
    total_items: Annotated[int, Field(title="Total Items")]


class SetEffortOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    effort_estimate: Annotated[str | None, Field(title="Effort Estimate")] = None
    op: Annotated[Literal["set_effort"], Field(title="Op")]
    subsection_id: Annotated[str, Field(title="Subsection Id")]


class SetSuggestedPathOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: Annotated[Literal["set_suggested_path"], Field(title="Op")]
    path: Annotated[list[str], Field(title="Path")] = []


class SetTagsOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: Annotated[Literal["set_tags"], Field(title="Op")]
    subsection_id: Annotated[str, Field(title="Subsection Id")]
    tags: Annotated[list[str], Field(title="Tags")] = []


class UpdateItemOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    item_id: Annotated[str, Field(title="Item Id")]
    op: Annotated[Literal["update_item"], Field(title="Op")]
    text: Annotated[str, Field(title="Text")]


class UpdateSectionOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: Annotated[Literal["update_section"], Field(title="Op")]
    section_id: Annotated[str, Field(title="Section Id")]
    title: Annotated[str, Field(min_length=1, title="Title")]


class UpdateSubsectionOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Annotated[str | None, Field(title="Description")] = None
    effort_estimate: Annotated[str | None, Field(title="Effort Estimate")] = None
    op: Annotated[Literal["update_subsection"], Field(title="Op")]
    subsection_id: Annotated[str, Field(title="Subsection Id")]
    title: Annotated[str | None, Field(min_length=1, title="Title")] = None


class Violation(BaseModel):
    ids: Annotated[list[str], Field(title="Ids")]
    message: Annotated[str, Field(title="Message")]
    rule: Annotated[str, Field(title="Rule")]


class ChangedNode(BaseModel):
    change: ChangeType
    id: Annotated[str, Field(title="Id")]
    kind: ChangedNodeKind


class OverviewDetails(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    description: Annotated[str | None, Field(title="Description")] = None
    owner: Annotated[str, Field(title="Owner")]
    published_visibility: PublishedVisibility
    subject_tags: Annotated[list[str], Field(title="Subject Tags")] = []
    suggested_path: Annotated[list[str], Field(title="Suggested Path")] = []
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class ProgressSnapshot(BaseModel):
    checked_ids: Annotated[list[str] | None, Field(title="Checked Ids")] = None
    checked_items: Annotated[int, Field(title="Checked Items")]
    deadline: Annotated[date | None, Field(title="Deadline")] = None
    percent: Annotated[int, Field(title="Percent")]
    roadmap_id: Annotated[str, Field(title="Roadmap Id")]
    sections: Annotated[list[SectionProgress], Field(title="Sections", validate_default=True)] = []
    total_items: Annotated[int, Field(title="Total Items")]


class Resource(BaseModel):
    id: Annotated[str, Field(title="Id")]
    title: Annotated[str, Field(title="Title")]
    type: ResourceType
    url: Annotated[str, Field(pattern="^https?://", title="Url")]


class ResourceInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    proposed_id: Annotated[str | None, Field(title="Proposed Id")] = None
    title: Annotated[str, Field(min_length=1, title="Title")]
    type: ResourceType
    url: Annotated[str, Field(pattern="^https?://", title="Url")]


class ResourceLink(BaseModel):
    title: Annotated[str, Field(title="Title")]
    type: ResourceType
    url: Annotated[str, Field(title="Url")]


class ResourceRef(BaseModel):
    id: Annotated[str, Field(title="Id")]
    title: Annotated[str, Field(title="Title")]
    type: ResourceType
    url: Annotated[str, Field(title="Url")]


class RoadmapCard(BaseModel):
    id: Annotated[str, Field(title="Id")]
    published_visibility: PublishedVisibility
    status: RoadmapStatus
    subject_tags: Annotated[list[str], Field(title="Subject Tags")] = []
    title: Annotated[str, Field(title="Title")]


class SearchHit(BaseModel):
    item_id: Annotated[str | None, Field(title="Item Id")] = None
    kind: SearchHitKind
    matched_tags: Annotated[list[str] | None, Field(title="Matched Tags")] = None
    subsection_id: Annotated[str, Field(title="Subsection Id")]
    title_or_text: Annotated[str, Field(title="Title Or Text")]


class SetResourcesOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    op: Annotated[Literal["set_resources"], Field(title="Op")]
    resources: Annotated[list[ResourceInput], Field(title="Resources", validate_default=True)] = []
    subsection_id: Annotated[str, Field(title="Subsection Id")]


class Subsection(BaseModel):
    checklist_items: Annotated[
        dict[str, ChecklistItem], Field(title="Checklist Items", validate_default=True)
    ] = {}
    description: Annotated[str | None, Field(title="Description")] = None
    effort_estimate: Annotated[str | None, Field(title="Effort Estimate")] = None
    id: Annotated[str, Field(title="Id")]
    item_order: Annotated[list[str], Field(title="Item Order")] = []
    prereq_ids: Annotated[list[str], Field(title="Prereq Ids")] = []
    resource_order: Annotated[list[str], Field(title="Resource Order")] = []
    resources: Annotated[dict[str, Resource], Field(title="Resources", validate_default=True)] = {}
    tags: Annotated[list[str], Field(title="Tags")] = []
    title: Annotated[str, Field(title="Title")]


class SubsectionInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    checklist_items: Annotated[
        list[ChecklistItemInput], Field(title="Checklist Items", validate_default=True)
    ] = []
    description: Annotated[str | None, Field(title="Description")] = None
    effort_estimate: Annotated[str | None, Field(title="Effort Estimate")] = None
    prereq_ids: Annotated[list[str], Field(title="Prereq Ids")] = []
    proposed_id: Annotated[str | None, Field(title="Proposed Id")] = None
    resources: Annotated[list[ResourceInput], Field(title="Resources", validate_default=True)] = []
    tags: Annotated[list[str], Field(title="Tags")] = []
    title: Annotated[str, Field(min_length=1, title="Title")]


class AddSubsectionOp(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    after_id: Annotated[str | None, Field(title="After Id")] = None
    before_id: Annotated[str | None, Field(title="Before Id")] = None
    op: Annotated[Literal["add_subsection"], Field(title="Op")]
    section_id: Annotated[str, Field(title="Section Id")]
    subsection: SubsectionInput


class Dashboard(BaseModel):
    authored: Annotated[list[RoadmapCard], Field(title="Authored", validate_default=True)] = []
    followed: Annotated[list[RoadmapCard], Field(title="Followed", validate_default=True)] = []


class NextItem(BaseModel):
    item_id: Annotated[str, Field(title="Item Id")]
    path_position: Annotated[int | None, Field(title="Path Position")] = None
    resources: Annotated[list[ResourceLink], Field(title="Resources", validate_default=True)] = []
    subsection_id: Annotated[str, Field(title="Subsection Id")]
    text: Annotated[str, Field(title="Text")]
    why_now: Annotated[str, Field(title="Why Now")]


class NextResult(BaseModel):
    complete: Annotated[bool, Field(title="Complete")] = False
    items: Annotated[list[NextItem], Field(title="Items", validate_default=True)] = []
    remaining_in_path: Annotated[int, Field(title="Remaining In Path")] = 0


class NodeDetail(BaseModel):
    description: Annotated[str | None, Field(title="Description")] = None
    effort_estimate: Annotated[str | None, Field(title="Effort Estimate")] = None
    items: Annotated[list[ItemState], Field(title="Items", validate_default=True)] = []
    prereqs: Annotated[list[PrereqRef], Field(title="Prereqs", validate_default=True)] = []
    resources: Annotated[list[ResourceRef], Field(title="Resources", validate_default=True)] = []
    subsection_id: Annotated[str, Field(title="Subsection Id")]
    tags: Annotated[list[str], Field(title="Tags")] = []
    title: Annotated[str, Field(title="Title")]


class Overview(BaseModel):
    details: OverviewDetails | None = None
    overall: OverallProgress
    revision: Annotated[int, Field(title="Revision")]
    roadmap_id: Annotated[str, Field(title="Roadmap Id")]
    sections: Annotated[list[SectionOverview], Field(title="Sections", validate_default=True)] = []
    status: RoadmapStatus
    title: Annotated[str, Field(title="Title")]


class Profile(BaseModel):
    display_name: Annotated[str, Field(title="Display Name")]
    handle: Annotated[str, Field(title="Handle")]
    roadmaps: Annotated[list[RoadmapCard], Field(title="Roadmaps", validate_default=True)] = []


class ProgressUpdateResult(BaseModel):
    next: NextResult
    progress: ProgressSnapshot


class Section(BaseModel):
    id: Annotated[str, Field(title="Id")]
    subsection_order: Annotated[list[str], Field(title="Subsection Order")] = []
    subsections: Annotated[
        dict[str, Subsection], Field(title="Subsections", validate_default=True)
    ] = {}
    title: Annotated[str, Field(title="Title")]


class SectionInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    proposed_id: Annotated[str | None, Field(title="Proposed Id")] = None
    subsections: Annotated[
        list[SubsectionInput], Field(title="Subsections", validate_default=True)
    ] = []
    title: Annotated[str, Field(min_length=1, title="Title")]


class SectionPage(BaseModel):
    include: SectionInclude
    next_cursor: Annotated[str | None, Field(title="Next Cursor")] = None
    section_id: Annotated[str, Field(title="Section Id")]
    steering: Annotated[str | None, Field(title="Steering")] = None
    subsections: Annotated[list[NodeDetail], Field(title="Subsections", validate_default=True)] = []
    title: Annotated[str, Field(title="Title")]


class Roadmap(BaseModel):
    created_at: Annotated[AwareDatetime, Field(title="Created At")]
    description: Annotated[str | None, Field(title="Description")] = None
    id: Annotated[str, Field(title="Id")]
    owner: Annotated[str, Field(title="Owner")]
    published_visibility: PublishedVisibility = PublishedVisibility.PUBLIC
    revision: Annotated[int, Field(title="Revision")] = 1
    section_order: Annotated[list[str], Field(title="Section Order")] = []
    sections: Annotated[dict[str, Section], Field(title="Sections", validate_default=True)] = {}
    status: RoadmapStatus = RoadmapStatus.DRAFT
    subject_tags: Annotated[list[str], Field(title="Subject Tags")] = []
    suggested_path: Annotated[list[str], Field(title="Suggested Path")] = []
    title: Annotated[str, Field(title="Title")]
    updated_at: Annotated[AwareDatetime, Field(title="Updated At")]


class RoadmapDraftInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: Annotated[str | None, Field(title="Description")] = None
    proposed_id: Annotated[str | None, Field(title="Proposed Id")] = None
    sections: Annotated[list[SectionInput], Field(title="Sections", validate_default=True)] = []
    subject_tags: Annotated[list[str], Field(title="Subject Tags")] = []
    suggested_path: Annotated[list[str], Field(title="Suggested Path")] = []
    title: Annotated[str, Field(min_length=1, title="Title")]
