/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Roadmap */
        post: operations["create_roadmap_roadmaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roadmap */
        get: operations["get_roadmap_roadmaps__roadmap_id__get"];
        /** Replace Roadmap */
        put: operations["replace_roadmap_roadmaps__roadmap_id__put"];
        post?: never;
        /** Delete Roadmap */
        delete: operations["delete_roadmap_roadmaps__roadmap_id__delete"];
        options?: never;
        head?: never;
        /** Patch Roadmap */
        patch: operations["patch_roadmap_roadmaps__roadmap_id__patch"];
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_roadmaps__roadmap_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/nodes/{subsection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Node */
        get: operations["get_node_roadmaps__roadmap_id__nodes__subsection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/sections/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Section */
        get: operations["get_section_roadmaps__roadmap_id__sections__section_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Roadmap */
        get: operations["search_roadmap_roadmaps__roadmap_id__search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}:validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Roadmap */
        post: operations["validate_roadmap_roadmaps__roadmap_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}:publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Roadmap */
        post: operations["publish_roadmap_roadmaps__roadmap_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}:fork": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fork Roadmap */
        post: operations["fork_roadmap_roadmaps__roadmap_id__fork_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Roadmap Metadata */
        patch: operations["edit_roadmap_metadata_roadmaps__roadmap_id__metadata_patch"];
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Roadmap Visibility */
        put: operations["set_roadmap_visibility_roadmaps__roadmap_id__visibility_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}:archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Roadmap */
        post: operations["archive_roadmap_roadmaps__roadmap_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Follow Roadmap */
        post: operations["follow_roadmap_roadmaps__roadmap_id__follow_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_roadmaps__roadmap_id__progress_get"];
        put?: never;
        /** Update Progress */
        post: operations["update_progress_roadmaps__roadmap_id__progress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Next */
        get: operations["get_next_roadmaps__roadmap_id__next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}/deadline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Deadline */
        put: operations["set_deadline_roadmaps__roadmap_id__deadline_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** As Metadata */
        get: operations["as_metadata__well_known_oauth_authorization_server_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jwks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jwks Document */
        get: operations["jwks_document_jwks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Client */
        post: operations["register_client_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize */
        get: operations["authorize_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize Context */
        get: operations["authorize_context_authorize_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize Decision */
        post: operations["authorize_decision_authorize_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token */
        post: operations["token_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_me_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Client */
        delete: operations["revoke_client_me_clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddEdgeOp
         * @description ``to_id`` gains ``from_id`` as a prerequisite (spec section 07).
         */
        AddEdgeOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_edge";
            /** From Id */
            from_id: string;
            /** To Id */
            to_id: string;
        };
        /** AddItemOp */
        AddItemOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_item";
            /** Subsection Id */
            subsection_id: string;
            /** Text */
            text: string;
            /** Proposed Id */
            proposed_id?: string | null;
            /** Before Id */
            before_id?: string | null;
            /** After Id */
            after_id?: string | null;
        };
        /** AddSectionOp */
        AddSectionOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_section";
            /** Title */
            title: string;
            /** Proposed Id */
            proposed_id?: string | null;
            /** Before Id */
            before_id?: string | null;
            /** After Id */
            after_id?: string | null;
        };
        /** AddSubsectionOp */
        AddSubsectionOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "add_subsection";
            /** Section Id */
            section_id: string;
            subsection: components["schemas"]["SubsectionInput"];
            /** Before Id */
            before_id?: string | null;
            /** After Id */
            after_id?: string | null;
        };
        /**
         * AuthenticatedUser
         * @description The authenticated user's own view, returned by register/login/refresh.
         *
         *     Carries the private ``email`` (the caller is the account owner) but never the
         *     password hash. The public, cross-user projection lives in ``PublicProfile``.
         */
        AuthenticatedUser: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AuthorizationContext
         * @description What the SPA consent screen renders for a parked ``auth_request_id``.
         */
        AuthorizationContext: {
            /** Client Name */
            client_name: string;
            /** Scopes */
            scopes: string[];
            /** Authenticated */
            authenticated: boolean;
        };
        /** Body_revoke_revoke_post */
        Body_revoke_revoke_post: {
            /** Token */
            token: string;
            /** Token Type Hint */
            token_type_hint?: string | null;
            /** Client Id */
            client_id?: string | null;
        };
        /** Body_token_token_post */
        Body_token_token_post: {
            /**
             * Grant Type
             * @default
             */
            grant_type: string;
            /** Client Id */
            client_id?: string | null;
            /** Code */
            code?: string | null;
            /** Code Verifier */
            code_verifier?: string | null;
            /** Redirect Uri */
            redirect_uri?: string | null;
            /** Refresh Token */
            refresh_token?: string | null;
            /** Resource */
            resource?: string | null;
        };
        /**
         * ChangeType
         * @enum {string}
         */
        ChangeType: "added" | "updated" | "removed";
        /**
         * ChangedNode
         * @description One node the batch touched, echoed back so the agent knows what changed
         *     without re-reading the whole roadmap (spec section 07: summary-first). Lean
         *     on purpose (kind + id + change), keeping a small edit's response near the
         *     ~50-token target; the agent re-reads a specific node for its new body.
         */
        ChangedNode: {
            kind: components["schemas"]["ChangedNodeKind"];
            /** Id */
            id: string;
            change: components["schemas"]["ChangeType"];
        };
        /**
         * ChangedNodeKind
         * @enum {string}
         */
        ChangedNodeKind: "roadmap" | "section" | "subsection" | "item";
        /**
         * ChecklistItem
         * @description The only checkable unit.
         */
        ChecklistItem: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** ChecklistItemInput */
        ChecklistItemInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Text */
            text: string;
        };
        /**
         * ClientRegistrationRequest
         * @description RFC 7591 registration input. Only ``redirect_uris`` is required at P0.
         */
        ClientRegistrationRequest: {
            /** Redirect Uris */
            redirect_uris: string[];
            /** Client Name */
            client_name?: string | null;
            /** Grant Types */
            grant_types?: string[] | null;
            /** Response Types */
            response_types?: string[] | null;
            /** Scope */
            scope?: string | null;
            /** Token Endpoint Auth Method */
            token_endpoint_auth_method?: string | null;
        };
        /**
         * ClientRegistrationResponse
         * @description RFC 7591 registration response echoing the stored client metadata.
         */
        ClientRegistrationResponse: {
            /** Client Id */
            client_id: string;
            /** Client Name */
            client_name: string;
            /** Redirect Uris */
            redirect_uris: string[];
            /** Grant Types */
            grant_types: string[];
            /** Response Types */
            response_types: string[];
            /** Scope */
            scope: string;
            /** Token Endpoint Auth Method */
            token_endpoint_auth_method: string;
            /** Client Id Issued At */
            client_id_issued_at: number;
        };
        /**
         * CompletionState
         * @description The explicit target state a ``progress_update`` sets its items to.
         *
         *     Explicit set, never toggle (spec section 07): the client states the desired
         *     state so a retry is idempotent.
         * @enum {string}
         */
        CompletionState: "complete" | "incomplete";
        /**
         * ConnectedClient
         * @description One authorized agent in the user's connected-clients list.
         */
        ConnectedClient: {
            /** Client Id */
            client_id: string;
            /** Client Name */
            client_name: string;
            /** Scopes */
            scopes: string[];
            /**
             * Last Authorized
             * Format: date-time
             */
            last_authorized: string;
        };
        /**
         * DeadlineRequest
         * @description The ``PUT /roadmaps/{id}/deadline`` body: set or clear the per-user deadline.
         *
         *     A ``date`` sets the deadline; ``null`` clears it. The deadline is editable and
         *     clearable at any time. A date in the past is allowed (the countdown shows
         *     elapsed / overdue with no pacing signal; spec sections 04/10/15).
         */
        DeadlineRequest: {
            /** Deadline */
            deadline?: string | null;
        };
        /**
         * DecisionRequest
         * @description The human's consent decision for a parked request.
         */
        DecisionRequest: {
            /** Auth Request Id */
            auth_request_id: string;
            /** Approve */
            approve: boolean;
        };
        /**
         * DecisionResult
         * @description The loopback URL the SPA redirects the browser to (approve or deny).
         *
         *     Returned as JSON (not a 302) because the SPA calls the decision endpoint via a
         *     credentialed XHR; the SPA performs the browser navigation to the loopback
         *     listener itself.
         */
        DecisionResult: {
            /** Redirect Uri */
            redirect_uri: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ItemState
         * @description A checklist item with the caller's done state (``done`` = checked).
         */
        ItemState: {
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Done */
            done: boolean;
        };
        /**
         * LoginRequest
         * @description Login input. ``email`` is a plain string (not ``EmailStr``) so a malformed
         *     address takes the same generic 401 path as a wrong password, never leaking
         *     whether the address is even well-formed vs. registered.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MetadataEditRequest
         * @description The ``PATCH /roadmaps/{id}/metadata`` body: the presentation-only fields
         *     that stay mutable after publish (spec sections 04/06).
         *
         *     Only ``title`` / ``description`` / ``subject_tags`` are editable here; a field
         *     left out (``None``) is unchanged (last-write-wins, deliberately not
         *     ``If-Match``-guarded and never bumps the structural ``revision``). ``extra`` is
         *     ``allow``ed so a smuggled structural, lifecycle, or identity field (e.g.
         *     ``sections`` / ``visibility`` / ``status`` / ``revision``) is *captured* rather
         *     than silently dropped, then rejected as immutable by
         *     :meth:`reject_structural_fields`: the metadata endpoint can never touch
         *     anything but presentation.
         */
        MetadataEditRequest: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * NextItem
         * @description One unchecked, prereq-satisfied checklist item to work on next.
         *
         *     ``why_now`` is a STRUCTURAL rationale only (spec section 07): it states the
         *     mechanical facts the app owns (this is the next unchecked subsection in
         *     ``suggested_path`` and its named prerequisites are complete), never
         *     pedagogical / ZPD judgement (that intelligence lives in the agent and was
         *     baked into ``suggested_path`` at authoring time). ``path_position`` (the
         *     1-based index of the item's subsection in ``suggested_path``) is populated
         *     only in ``detailed`` mode.
         */
        NextItem: {
            /** Subsection Id */
            subsection_id: string;
            /** Item Id */
            item_id: string;
            /** Text */
            text: string;
            /** Why Now */
            why_now: string;
            /** Resources */
            resources?: components["schemas"]["ResourceLink"][];
            /** Path Position */
            path_position?: number | null;
        };
        /**
         * NextResult
         * @description The ``GET /next`` body: the next unchecked items in ``suggested_path``
         *     order whose prerequisites are all complete (spec section 07).
         *
         *     ``remaining_in_path`` counts the subsections still to do along the path (any
         *     with an unchecked item); ``complete`` is ``True`` when nothing remains.
         */
        NextResult: {
            /** Items */
            items?: components["schemas"]["NextItem"][];
            /**
             * Remaining In Path
             * @default 0
             */
            remaining_in_path: number;
            /**
             * Complete
             * @default false
             */
            complete: boolean;
        };
        /**
         * NodeDetail
         * @description One subsection resolved for study (spec section 04 ``NodeDetail``).
         *
         *     ``description`` is populated only in ``detailed`` mode; the concise projection
         *     leaves it ``None`` while still carrying every follow-up ID (the subsection id,
         *     the resource links, the resolved prereq ids, and the item ids). External
         *     bodies are never inlined: ``resources`` are links only.
         */
        NodeDetail: {
            /** Subsection Id */
            subsection_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[];
            /** Effort Estimate */
            effort_estimate?: string | null;
            /** Resources */
            resources?: components["schemas"]["ResourceRef"][];
            /** Prereqs */
            prereqs?: components["schemas"]["PrereqRef"][];
            /** Items */
            items?: components["schemas"]["ItemState"][];
        };
        /**
         * OverallProgress
         * @description Roadmap-wide completion totals (derived, never stored).
         */
        OverallProgress: {
            /** Total Items */
            total_items: number;
            /** Checked Items */
            checked_items: number;
            /** Percent */
            percent: number;
        };
        /**
         * Overview
         * @description The ``GET /overview`` body: sections in ``section_order`` with per-section
         *     and overall completion, and no checklist-item bodies (spec section 04).
         *
         *     The orientation call; from here the agent drills into a node (``get_node``) or
         *     a section (``get_section``). ``checked_items`` / ``percent`` reflect the
         *     caller's own progress (zero when they have not started).
         */
        Overview: {
            /** Roadmap Id */
            roadmap_id: string;
            /** Title */
            title: string;
            status: components["schemas"]["RoadmapStatus"];
            /** Revision */
            revision: number;
            /** Sections */
            sections?: components["schemas"]["SectionOverview"][];
            overall: components["schemas"]["OverallProgress"];
        };
        /**
         * PatchRequest
         * @description The ``PATCH /roadmaps/{id}`` body: the ordered op list applied atomically.
         *
         *     The target ``revision`` travels in the ``If-Match`` header (spec section 06),
         *     not the body. At least one op is required so a patch is never a silent no-op
         *     that would still burn a revision.
         */
        PatchRequest: {
            /** Operations */
            operations: (components["schemas"]["AddSubsectionOp"] | components["schemas"]["UpdateSubsectionOp"] | components["schemas"]["RemoveSubsectionOp"] | components["schemas"]["AddEdgeOp"] | components["schemas"]["RemoveEdgeOp"] | components["schemas"]["SetTagsOp"] | components["schemas"]["SetResourcesOp"] | components["schemas"]["SetEffortOp"] | components["schemas"]["AddItemOp"] | components["schemas"]["UpdateItemOp"] | components["schemas"]["RemoveItemOp"] | components["schemas"]["ReorderOp"] | components["schemas"]["SetSuggestedPathOp"] | components["schemas"]["AddSectionOp"] | components["schemas"]["UpdateSectionOp"] | components["schemas"]["RemoveSectionOp"])[];
        };
        /**
         * PatchResult
         * @description The ``PATCH /roadmaps/{id}`` body: the post-batch ``revision``, the changed
         *     nodes, and the ``proposed_id -> minted_id`` remap for any de-duped ``add_*``
         *     proposal (spec section 07). ``remap`` is empty when nothing was de-duped.
         */
        PatchResult: {
            /** Roadmap Id */
            roadmap_id: string;
            /** Revision */
            revision: number;
            /** Changed Nodes */
            changed_nodes?: components["schemas"]["ChangedNode"][];
            /** Remap */
            remap?: {
                [key: string]: string;
            };
        };
        /**
         * PrereqRef
         * @description A resolved prerequisite: its id, title, and the caller's done state.
         *
         *     ``done`` is ``True`` when the caller has completed every checklist item of the
         *     prerequisite subsection (so an agent can see at a glance whether this node is
         *     unlocked).
         */
        PrereqRef: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Done */
            done: boolean;
        };
        /**
         * Progress
         * @description A user's progress against one roadmap (spec section 04).
         *
         *     ``checked`` maps a checklist-item id to its checked state; only checked items
         *     are retained (an unchecked item is simply absent), which keeps the map lean
         *     and the explicit-set idempotent. ``user_id`` is resolved from the
         *     token/session and never trusted from args. This is the ``follow`` response
         *     body (following creates the record).
         */
        Progress: {
            /** User Id */
            user_id: string;
            /** Roadmap Id */
            roadmap_id: string;
            /** Deadline */
            deadline?: string | null;
            /** Checked */
            checked?: {
                [key: string]: boolean;
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProgressSnapshot
         * @description The ``GET /progress`` body: roadmap-wide + per-section completion.
         *
         *     ``checked_ids`` is populated only in ``detailed`` mode (spec section 04),
         *     keeping the default concise response small while still letting a client
         *     reconcile the exact checked set when it asks for it.
         */
        ProgressSnapshot: {
            /** Roadmap Id */
            roadmap_id: string;
            /** Total Items */
            total_items: number;
            /** Checked Items */
            checked_items: number;
            /** Percent */
            percent: number;
            /** Deadline */
            deadline?: string | null;
            /** Sections */
            sections?: components["schemas"]["SectionProgress"][];
            /** Checked Ids */
            checked_ids?: string[] | null;
        };
        /**
         * ProgressUpdateRequest
         * @description The ``POST /progress`` body: set ``item_ids`` to ``state`` (explicit set,
         *     not toggle; spec section 07). At least one id is required so an update is
         *     never a silent no-op.
         */
        ProgressUpdateRequest: {
            /** Item Ids */
            item_ids: string[];
            state: components["schemas"]["CompletionState"];
        };
        /**
         * ProgressUpdateResult
         * @description The ``POST /progress`` body: the fresh snapshot after the set plus the
         *     next suggestion (spec sections 04/07). The snapshot is returned in detailed
         *     mode so the client can reconcile its checkbox state to the server truth.
         */
        ProgressUpdateResult: {
            progress: components["schemas"]["ProgressSnapshot"];
            next: components["schemas"]["NextResult"];
        };
        /**
         * RegisterRequest
         * @description Registration input. Structural typing only; domain rules (password
         *     strength, handle charset) are enforced in the service for specific messages.
         */
        RegisterRequest: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RemoveEdgeOp */
        RemoveEdgeOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_edge";
            /** From Id */
            from_id: string;
            /** To Id */
            to_id: string;
        };
        /** RemoveItemOp */
        RemoveItemOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_item";
            /** Item Id */
            item_id: string;
        };
        /** RemoveSectionOp */
        RemoveSectionOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_section";
            /** Section Id */
            section_id: string;
        };
        /** RemoveSubsectionOp */
        RemoveSubsectionOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "remove_subsection";
            /** Subsection Id */
            subsection_id: string;
        };
        /**
         * ReorderOp
         * @description Move any node (section / subsection / item) within its sibling order.
         */
        ReorderOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "reorder";
            /** Target Id */
            target_id: string;
            /** Before Id */
            before_id?: string | null;
            /** After Id */
            after_id?: string | null;
        };
        /**
         * Resource
         * @description An external link on a subsection; the body is never inlined.
         */
        Resource: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            type: components["schemas"]["ResourceType"];
        };
        /** ResourceInput */
        ResourceInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            type: components["schemas"]["ResourceType"];
        };
        /**
         * ResourceLink
         * @description A resource reference on a next item: a link, never an inlined body.
         */
        ResourceLink: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            type: components["schemas"]["ResourceType"];
        };
        /**
         * ResourceRef
         * @description A subsection resource as a link, never an inlined body (spec section 07).
         */
        ResourceRef: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            type: components["schemas"]["ResourceType"];
        };
        /**
         * ResourceType
         * @enum {string}
         */
        ResourceType: "article" | "video" | "book" | "course" | "docs" | "other";
        /**
         * ResponseFormat
         * @description The ``concise | detailed`` switch on the read tools (spec section 07).
         *
         *     Concise is roughly one-third the tokens and still carries the follow-up IDs;
         *     detailed adds the explanatory free-text (the node ``description``).
         * @enum {string}
         */
        ResponseFormat: "concise" | "detailed";
        /**
         * Roadmap
         * @description A roadmap definition owned by one user. ``owner`` is resolved from the
         *     session, never trusted from client input.
         */
        Roadmap: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[];
            /** @default private */
            visibility: components["schemas"]["Visibility"];
            /** @default draft */
            status: components["schemas"]["RoadmapStatus"];
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["Section"];
            };
            /** Section Order */
            section_order?: string[];
            /** Suggested Path */
            suggested_path?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RoadmapCreated
         * @description The ``POST /roadmaps`` body: the full minted roadmap plus a ``remap`` of
         *     every de-duped ``proposed_id -> minted_id`` so the author can reconcile the
         *     references it sent (spec section 04). ``remap`` is empty when no proposed ID
         *     had to be changed.
         */
        RoadmapCreated: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[];
            /** @default private */
            visibility: components["schemas"]["Visibility"];
            /** @default draft */
            status: components["schemas"]["RoadmapStatus"];
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["Section"];
            };
            /** Section Order */
            section_order?: string[];
            /** Suggested Path */
            suggested_path?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Remap */
            remap?: {
                [key: string]: string;
            };
        };
        /**
         * RoadmapInput
         * @description The ``create_roadmap_draft`` / ``replace_roadmap_draft`` payload.
         */
        RoadmapInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[];
            /** @default private */
            visibility: components["schemas"]["Visibility"];
            /** Sections */
            sections?: components["schemas"]["SectionInput"][];
            /** Suggested Path */
            suggested_path?: string[];
        };
        /**
         * RoadmapReplaced
         * @description The ``PUT /roadmaps/{id}`` body: the full rebuilt draft after a full-document
         *     import (the escape hatch, spec section 07) plus the ``proposed_id -> minted_id``
         *     remap. Mirrors :class:`RoadmapCreated` because replace reuses the same
         *     mint-then-resolve assembly: ``proposed_id``s are preserved, every other node is
         *     re-minted, and the roadmap's own ID is unchanged (spec section 04). ``remap`` is
         *     empty when no proposed ID had to be de-duped.
         */
        RoadmapReplaced: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[];
            /** @default private */
            visibility: components["schemas"]["Visibility"];
            /** @default draft */
            status: components["schemas"]["RoadmapStatus"];
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["Section"];
            };
            /** Section Order */
            section_order?: string[];
            /** Suggested Path */
            suggested_path?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Remap */
            remap?: {
                [key: string]: string;
            };
        };
        /**
         * RoadmapStatus
         * @enum {string}
         */
        RoadmapStatus: "draft" | "published" | "archived";
        /**
         * SearchHit
         * @description One search match, carrying the IDs needed to drill down (spec section 04).
         *
         *     ``item_id`` is present only when ``kind == item``; ``matched_tags`` names the
         *     subsection tags that matched a tag filter (absent for a keyword-only match).
         */
        SearchHit: {
            kind: components["schemas"]["SearchHitKind"];
            /** Subsection Id */
            subsection_id: string;
            /** Item Id */
            item_id?: string | null;
            /** Title Or Text */
            title_or_text: string;
            /** Matched Tags */
            matched_tags?: string[] | null;
        };
        /**
         * SearchHitKind
         * @description Whether a search hit is a subsection (DAG node) or a checklist item.
         * @enum {string}
         */
        SearchHitKind: "subsection" | "item";
        /**
         * Section
         * @description An ordered phase grouping DAG-node subsections.
         */
        Section: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subsections */
            subsections?: {
                [key: string]: components["schemas"]["Subsection"];
            };
            /** Subsection Order */
            subsection_order?: string[];
        };
        /**
         * SectionInclude
         * @description Which parts of each node a ``SectionPage`` populates (spec section 07).
         *
         *     ``subsections`` = node metadata (tags, effort, resources, resolved prereqs);
         *     ``items`` = the checklist items only; ``both`` = everything. Every variant
         *     still carries the ``subsection_id`` so the agent can drill in further.
         * @enum {string}
         */
        SectionInclude: "subsections" | "items" | "both";
        /** SectionInput */
        SectionInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Subsections */
            subsections?: components["schemas"]["SubsectionInput"][];
        };
        /**
         * SectionOverview
         * @description Per-section completion counts, no checklist-item bodies (spec section 04).
         */
        SectionOverview: {
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
            /** Total Items */
            total_items: number;
            /** Checked Items */
            checked_items: number;
            /** Percent */
            percent: number;
        };
        /**
         * SectionPage
         * @description The ``GET /sections/{sid}`` body: a paginated section drill-down (spec
         *     sections 04/07).
         *
         *     ``include`` selects which parts of each node are populated. The page holds a
         *     server-set number of subsections in ``subsection_order``; ``next_cursor`` is
         *     an **opaque** token for the next page (absent on the last page) and
         *     ``steering`` is present only when the response was truncated.
         */
        SectionPage: {
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
            include: components["schemas"]["SectionInclude"];
            /** Subsections */
            subsections?: components["schemas"]["NodeDetail"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Steering */
            steering?: string | null;
        };
        /**
         * SectionProgress
         * @description Per-section completion counts, derived from progress + roadmap.
         */
        SectionProgress: {
            /** Section Id */
            section_id: string;
            /** Total Items */
            total_items: number;
            /** Checked Items */
            checked_items: number;
            /** Percent */
            percent: number;
        };
        /** SetEffortOp */
        SetEffortOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_effort";
            /** Subsection Id */
            subsection_id: string;
            /** Effort Estimate */
            effort_estimate?: string | null;
        };
        /** SetResourcesOp */
        SetResourcesOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_resources";
            /** Subsection Id */
            subsection_id: string;
            /** Resources */
            resources?: components["schemas"]["ResourceInput"][];
        };
        /** SetSuggestedPathOp */
        SetSuggestedPathOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_suggested_path";
            /** Path */
            path?: string[];
        };
        /** SetTagsOp */
        SetTagsOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "set_tags";
            /** Subsection Id */
            subsection_id: string;
            /** Tags */
            tags?: string[];
        };
        /**
         * Subsection
         * @description The DAG node: track tags, resources, checklist items, prereq edges.
         */
        Subsection: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[];
            /** Effort Estimate */
            effort_estimate?: string | null;
            /** Prereq Ids */
            prereq_ids?: string[];
            /** Resources */
            resources?: {
                [key: string]: components["schemas"]["Resource"];
            };
            /** Resource Order */
            resource_order?: string[];
            /** Checklist Items */
            checklist_items?: {
                [key: string]: components["schemas"]["ChecklistItem"];
            };
            /** Item Order */
            item_order?: string[];
        };
        /** SubsectionInput */
        SubsectionInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[];
            /** Effort Estimate */
            effort_estimate?: string | null;
            /** Prereq Ids */
            prereq_ids?: string[];
            /** Resources */
            resources?: components["schemas"]["ResourceInput"][];
            /** Checklist Items */
            checklist_items?: components["schemas"]["ChecklistItemInput"][];
        };
        /** UpdateItemOp */
        UpdateItemOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "update_item";
            /** Item Id */
            item_id: string;
            /** Text */
            text: string;
        };
        /** UpdateSectionOp */
        UpdateSectionOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "update_section";
            /** Section Id */
            section_id: string;
            /** Title */
            title: string;
        };
        /** UpdateSubsectionOp */
        UpdateSubsectionOp: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            op: "update_subsection";
            /** Subsection Id */
            subsection_id: string;
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Effort Estimate */
            effort_estimate?: string | null;
        };
        /**
         * ValidateResult
         * @description The ``POST /roadmaps/{id}:validate`` body: all structural violations in one
         *     pass (empty when the draft is publishable). The ``violations`` shape is
         *     identical to the 422 publish hard-block body (spec section 06), so a client
         *     handles one violation contract for both validate and publish.
         */
        ValidateResult: {
            /** Violations */
            violations?: components["schemas"]["Violation"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Violation
         * @description One structural rule failure, model-recoverable by naming the rule and IDs.
         *
         *     Produced by the structural validator (spec section 05 ``validation.py``, a
         *     later slice) and carried in a ``Validation`` error's problem+json body. Lives
         *     in the error contract because it is part of the wire shape every client reads.
         */
        Violation: {
            /** Rule */
            rule: string;
            /** Ids */
            ids: string[];
            /** Message */
            message: string;
        };
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "public" | "private";
        /**
         * VisibilityRequest
         * @description The ``PUT /roadmaps/{id}/visibility`` body: toggle public/private (web-only,
         *     spec sections 04/06).
         *
         *     Visibility is a lifecycle/presentation field, editable by the owner on a
         *     roadmap of any status (draft or published): a public roadmap is reachable by
         *     link and appears on the owner's profile, a private one is owner-only. The
         *     toggle is last-write-wins (never ``If-Match``-guarded) and touches no
         *     follower-visible structure, so it never bumps the structural ``revision``.
         */
        VisibilityRequest: {
            visibility: components["schemas"]["Visibility"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_roadmap_roadmaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roadmap_roadmaps__roadmap_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_roadmap_roadmaps__roadmap_id__put: {
        parameters: {
            query?: never;
            header: {
                "If-Match": number;
            };
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapReplaced"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_roadmap_roadmaps__roadmap_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_roadmap_roadmaps__roadmap_id__patch: {
        parameters: {
            query?: never;
            header: {
                "If-Match": number;
            };
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_roadmaps__roadmap_id__overview_get: {
        parameters: {
            query?: {
                format?: components["schemas"]["ResponseFormat"];
            };
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_node_roadmaps__roadmap_id__nodes__subsection_id__get: {
        parameters: {
            query?: {
                format?: components["schemas"]["ResponseFormat"];
            };
            header?: never;
            path: {
                roadmap_id: string;
                subsection_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_section_roadmaps__roadmap_id__sections__section_id__get: {
        parameters: {
            query?: {
                cursor?: string | null;
                include?: components["schemas"]["SectionInclude"];
            };
            header?: never;
            path: {
                roadmap_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_roadmap_roadmaps__roadmap_id__search_get: {
        parameters: {
            query?: {
                q?: string | null;
                tags?: string[] | null;
            };
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_roadmap_roadmaps__roadmap_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_roadmap_roadmaps__roadmap_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fork_roadmap_roadmaps__roadmap_id__fork_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_roadmap_metadata_roadmaps__roadmap_id__metadata_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetadataEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_roadmap_visibility_roadmaps__roadmap_id__visibility_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_roadmap_roadmaps__roadmap_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    follow_roadmap_roadmaps__roadmap_id__follow_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_roadmaps__roadmap_id__progress_get: {
        parameters: {
            query?: {
                detailed?: boolean;
            };
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_progress_roadmaps__roadmap_id__progress_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressUpdateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_roadmaps__roadmap_id__next_get: {
        parameters: {
            query?: {
                format?: components["schemas"]["ResponseFormat"];
            };
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_deadline_roadmaps__roadmap_id__deadline_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeadlineRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    as_metadata__well_known_oauth_authorization_server_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    jwks_document_jwks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_client_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_authorize_get: {
        parameters: {
            query?: {
                client_id?: string;
                redirect_uri?: string;
                response_type?: string;
                code_challenge?: string;
                code_challenge_method?: string;
                scope?: string | null;
                state?: string | null;
                resource?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_context_authorize_context_get: {
        parameters: {
            query: {
                auth_request_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_decision_authorize_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_token_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_revoke_revoke_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_me_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedClient"][];
                };
            };
        };
    };
    revoke_client_me_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
