/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Roadmap */
        post: operations["create_roadmap_roadmaps_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roadmaps/{roadmap_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roadmap */
        get: operations["get_roadmap_roadmaps__roadmap_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** As Metadata */
        get: operations["as_metadata__well_known_oauth_authorization_server_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jwks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jwks Document */
        get: operations["jwks_document_jwks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Client */
        post: operations["register_client_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize */
        get: operations["authorize_authorize_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize Context */
        get: operations["authorize_context_authorize_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorize/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authorize Decision */
        post: operations["authorize_decision_authorize_decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Token */
        post: operations["token_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke */
        post: operations["revoke_revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients */
        get: operations["list_clients_me_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Client */
        delete: operations["revoke_client_me_clients__client_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuthenticatedUser
         * @description The authenticated user's own view, returned by register/login/refresh.
         *
         *     Carries the private ``email`` (the caller is the account owner) but never the
         *     password hash. The public, cross-user projection lives in ``PublicProfile``.
         */
        AuthenticatedUser: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * AuthorizationContext
         * @description What the SPA consent screen renders for a parked ``auth_request_id``.
         */
        AuthorizationContext: {
            /** Client Name */
            client_name: string;
            /** Scopes */
            scopes: string[];
            /** Authenticated */
            authenticated: boolean;
        };
        /** Body_revoke_revoke_post */
        Body_revoke_revoke_post: {
            /** Token */
            token: string;
            /** Token Type Hint */
            token_type_hint?: string | null;
            /** Client Id */
            client_id?: string | null;
        };
        /** Body_token_token_post */
        Body_token_token_post: {
            /**
             * Grant Type
             * @default
             */
            grant_type: string;
            /** Client Id */
            client_id?: string | null;
            /** Code */
            code?: string | null;
            /** Code Verifier */
            code_verifier?: string | null;
            /** Redirect Uri */
            redirect_uri?: string | null;
            /** Refresh Token */
            refresh_token?: string | null;
            /** Resource */
            resource?: string | null;
        };
        /**
         * ChecklistItem
         * @description The only checkable unit.
         */
        ChecklistItem: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** ChecklistItemInput */
        ChecklistItemInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Text */
            text: string;
        };
        /**
         * ClientRegistrationRequest
         * @description RFC 7591 registration input. Only ``redirect_uris`` is required at P0.
         */
        ClientRegistrationRequest: {
            /** Redirect Uris */
            redirect_uris: string[];
            /** Client Name */
            client_name?: string | null;
            /** Grant Types */
            grant_types?: string[] | null;
            /** Response Types */
            response_types?: string[] | null;
            /** Scope */
            scope?: string | null;
            /** Token Endpoint Auth Method */
            token_endpoint_auth_method?: string | null;
        };
        /**
         * ClientRegistrationResponse
         * @description RFC 7591 registration response echoing the stored client metadata.
         */
        ClientRegistrationResponse: {
            /** Client Id */
            client_id: string;
            /** Client Name */
            client_name: string;
            /** Redirect Uris */
            redirect_uris: string[];
            /** Grant Types */
            grant_types: string[];
            /** Response Types */
            response_types: string[];
            /** Scope */
            scope: string;
            /** Token Endpoint Auth Method */
            token_endpoint_auth_method: string;
            /** Client Id Issued At */
            client_id_issued_at: number;
        };
        /**
         * ConnectedClient
         * @description One authorized agent in the user's connected-clients list.
         */
        ConnectedClient: {
            /** Client Id */
            client_id: string;
            /** Client Name */
            client_name: string;
            /** Scopes */
            scopes: string[];
            /**
             * Last Authorized
             * Format: date-time
             */
            last_authorized: string;
        };
        /**
         * DecisionRequest
         * @description The human's consent decision for a parked request.
         */
        DecisionRequest: {
            /** Auth Request Id */
            auth_request_id: string;
            /** Approve */
            approve: boolean;
        };
        /**
         * DecisionResult
         * @description The loopback URL the SPA redirects the browser to (approve or deny).
         *
         *     Returned as JSON (not a 302) because the SPA calls the decision endpoint via a
         *     credentialed XHR; the SPA performs the browser navigation to the loopback
         *     listener itself.
         */
        DecisionResult: {
            /** Redirect Uri */
            redirect_uri: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Login input. ``email`` is a plain string (not ``EmailStr``) so a malformed
         *     address takes the same generic 401 path as a wrong password, never leaking
         *     whether the address is even well-formed vs. registered.
         */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * RegisterRequest
         * @description Registration input. Structural typing only; domain rules (password
         *     strength, handle charset) are enforced in the service for specific messages.
         */
        RegisterRequest: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * Resource
         * @description An external link on a subsection; the body is never inlined.
         */
        Resource: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Url */
            url: string;
            type: components["schemas"]["ResourceType"];
        };
        /** ResourceInput */
        ResourceInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Url */
            url: string;
            type: components["schemas"]["ResourceType"];
        };
        /**
         * ResourceType
         * @enum {string}
         */
        ResourceType: "article" | "video" | "book" | "course" | "docs" | "other";
        /**
         * Roadmap
         * @description A roadmap definition owned by one user. ``owner`` is resolved from the
         *     session, never trusted from client input.
         */
        Roadmap: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[];
            /** @default private */
            visibility: components["schemas"]["Visibility"];
            /** @default draft */
            status: components["schemas"]["RoadmapStatus"];
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["Section"];
            };
            /** Section Order */
            section_order?: string[];
            /** Suggested Path */
            suggested_path?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * RoadmapCreated
         * @description The ``POST /roadmaps`` body: the full minted roadmap plus a ``remap`` of
         *     every de-duped ``proposed_id -> minted_id`` so the author can reconcile the
         *     references it sent (spec section 04). ``remap`` is empty when no proposed ID
         *     had to be changed.
         */
        RoadmapCreated: {
            /** Id */
            id: string;
            /** Owner */
            owner: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[];
            /** @default private */
            visibility: components["schemas"]["Visibility"];
            /** @default draft */
            status: components["schemas"]["RoadmapStatus"];
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /** Sections */
            sections?: {
                [key: string]: components["schemas"]["Section"];
            };
            /** Section Order */
            section_order?: string[];
            /** Suggested Path */
            suggested_path?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Remap */
            remap?: {
                [key: string]: string;
            };
        };
        /**
         * RoadmapInput
         * @description The ``create_roadmap_draft`` / ``replace_roadmap_draft`` payload.
         */
        RoadmapInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Subject Tags */
            subject_tags?: string[];
            /** @default private */
            visibility: components["schemas"]["Visibility"];
            /** Sections */
            sections?: components["schemas"]["SectionInput"][];
            /** Suggested Path */
            suggested_path?: string[];
        };
        /**
         * RoadmapStatus
         * @enum {string}
         */
        RoadmapStatus: "draft" | "published" | "archived";
        /**
         * Section
         * @description An ordered phase grouping DAG-node subsections.
         */
        Section: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Subsections */
            subsections?: {
                [key: string]: components["schemas"]["Subsection"];
            };
            /** Subsection Order */
            subsection_order?: string[];
        };
        /** SectionInput */
        SectionInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Subsections */
            subsections?: components["schemas"]["SubsectionInput"][];
        };
        /**
         * Subsection
         * @description The DAG node: track tags, resources, checklist items, prereq edges.
         */
        Subsection: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[];
            /** Effort Estimate */
            effort_estimate?: string | null;
            /** Prereq Ids */
            prereq_ids?: string[];
            /** Resources */
            resources?: {
                [key: string]: components["schemas"]["Resource"];
            };
            /** Resource Order */
            resource_order?: string[];
            /** Checklist Items */
            checklist_items?: {
                [key: string]: components["schemas"]["ChecklistItem"];
            };
            /** Item Order */
            item_order?: string[];
        };
        /** SubsectionInput */
        SubsectionInput: {
            /** Proposed Id */
            proposed_id?: string | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Tags */
            tags?: string[];
            /** Effort Estimate */
            effort_estimate?: string | null;
            /** Prereq Ids */
            prereq_ids?: string[];
            /** Resources */
            resources?: components["schemas"]["ResourceInput"][];
            /** Checklist Items */
            checklist_items?: components["schemas"]["ChecklistItemInput"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Visibility
         * @enum {string}
         */
        Visibility: "public" | "private";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUser"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_roadmap_roadmaps_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoadmapInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roadmap_roadmaps__roadmap_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roadmap_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roadmap"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    as_metadata__well_known_oauth_authorization_server_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    jwks_document_jwks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_client_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRegistrationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientRegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_authorize_get: {
        parameters: {
            query?: {
                client_id?: string;
                redirect_uri?: string;
                response_type?: string;
                code_challenge?: string;
                code_challenge_method?: string;
                scope?: string | null;
                state?: string | null;
                resource?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_context_authorize_context_get: {
        parameters: {
            query: {
                auth_request_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationContext"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_decision_authorize_decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    token_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_token_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_revoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_revoke_revoke_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_clients_me_clients_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectedClient"][];
                };
            };
        };
    };
    revoke_client_me_clients__client_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
