"""The shared SQLAlchemy declarative base.

Every domain's ORM models (accounts #6, roadmaps #7+) inherit from this one
:class:`Base`, so ``Base.metadata`` is the single schema Alembic diffs for
``--autogenerate`` (spec section 11: one source of truth for the schema). The
constraint naming convention makes constraint names deterministic and stable, so
Alembic can emit reversible ``DROP CONSTRAINT`` operations and migrations read
the same across environments.

A domain registers its tables simply by defining models that subclass ``Base``;
``alembic/env.py`` imports those modules so the tables attach to this metadata.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Deterministic constraint names (indexes, uniques, checks, FKs, PKs). Without a
# convention SQLAlchemy leaves some constraints unnamed, which makes autogenerated
# downgrade steps unreliable.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every domain's ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
